#!/usr/bin/env bash

VERSION="1.1.0";

SAVEDIR="/usr/local/bin/";
BASEDIR="/usr/local/bin/";

for ARGUMENT in "$@"
do
  KEY=$(echo $ARGUMENT | cut -f1 -d=)
  VALUE=$(echo $ARGUMENT | cut -f2 -d=)

  case "$KEY" in
    -B|--base-dir)      BASEDIR=${VALUE} ;;
    -s|--save-dir)      SAVEDIR=${VALUE} ;;
    *)
  esac
done

mkdir "${BASEDIR}mcp";
curl https://raw.githubusercontent.com/00F100/magento-cloud/master/magento-create-project -o "${SAVEDIR}magento-create-project";
curl https://raw.githubusercontent.com/00F100/magento-cloud/master/mcp/build -o "${BASEDIR}mcp/build";
curl https://raw.githubusercontent.com/00F100/magento-cloud/master/mcp/clone -o "${BASEDIR}mcp/clone";
curl https://raw.githubusercontent.com/00F100/magento-cloud/master/mcp/deploy -o "${BASEDIR}mcp/deploy";
curl https://raw.githubusercontent.com/00F100/magento-cloud/master/mcp/docker-env-check -o "${BASEDIR}mcp/docker-env-check";
curl https://raw.githubusercontent.com/00F100/magento-cloud/master/mcp/format -o "${BASEDIR}mcp/format";
curl https://raw.githubusercontent.com/00F100/magento-cloud/master/mcp/helpers -o "${BASEDIR}mcp/helpers";
curl https://raw.githubusercontent.com/00F100/magento-cloud/master/mcp/inputs -o "${BASEDIR}mcp/inputs";
chmod +x "${SAVEDIR}magento-create-project";

magento-create-project --help