#!/usr/bin/env bash

VERSION="1.1.0";
BASEDIR="/usr/local/bin/";

for ARGUMENT in "$@"
do
  KEY=$(echo $ARGUMENT | cut -f1 -d=)
  VALUE=$(echo $ARGUMENT | cut -f2 -d=)

  case "$KEY" in
    -B|--base-dir)      BASEDIR=${VALUE} ;;
    *)
  esac
done

#####################################################
#                                                   #
#                      HELPERS                      #
#                                                   #
#####################################################
source "${BASEDIR}mcp/format";
source "${BASEDIR}mcp/helpers";

#####################################################
#                                                   #
#                 SYSTEM VALIDATION                 #
#                                                   #
#####################################################
source "${BASEDIR}mcp/docker-env-check";

#####################################################
#                                                   #
#                  INPUTS CONFIGS                   #
#                                                   #
#####################################################
source "${BASEDIR}mcp/inputs";

#####################################################
#                                                   #
#                   CLONING CLOUD                   #
#                                                   #
#####################################################
source "${BASEDIR}mcp/clone";

#####################################################
#                                                   #
#                     BUILDING                      #
#                                                   #
#####################################################
source "${BASEDIR}mcp/build";

#####################################################
#                                                   #
#                     DEPLOYING                     #
#                                                   #
#####################################################
source "${BASEDIR}mcp/deploy";