#!/usr/bin/env bash

SAVEDIR="/usr/local/bin/"
BASEDIR="/usr/local/bin/"

for ARGUMENT in "$@"
do
  KEY=$(echo $ARGUMENT | cut -f1 -d=)
  VALUE=$(echo $ARGUMENT | cut -f2 -d=)

  case "$KEY" in
    -B|--base-dir)      BASEDIR=${VALUE} ;;
    -s|--save-dir)      SAVEDIR=${VALUE} ;;
    *)
  esac
done

rm "${SAVEDIR}magento-create-project";
rm -R "${BASEDIR}mcp";
